"""Foundation abstractions and base interface for TrustRAG specialized agents."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import time
from typing import Any, Dict, Optional


class AgentError(Exception):
    """Base exception for all agent operations in TrustRAG."""
    pass


class AgentExecutionError(AgentError):
    """Raised when an agent encounters an internal runtime failure during execution."""
    pass


class AgentInputError(AgentError):
    """Raised when an agent receives invalid or malformed input arguments."""
    pass


@dataclass(frozen=True)
class AgentResult:
    """Standardized wrapper for agent execution outputs.

    Attributes:
        agent_name: Name of the executing agent.
        success: Whether the agent finished successfully.
        data: Output payload generated by the agent.
        error_message: Optional error message if execution failed.
        latency_seconds: Duration of execution in seconds.
        metadata: Additional diagnostic key-values.
    """

    agent_name: str
    success: bool
    data: Any
    error_message: Optional[str] = None
    latency_seconds: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize result to dictionary."""
        return {
            "agent_name": self.agent_name,
            "success": self.success,
            "data": self.data.to_dict() if hasattr(self.data, "to_dict") else self.data,
            "error_message": self.error_message,
            "latency_seconds": self.latency_seconds,
            "metadata": dict(self.metadata),
        }


class BaseAgent(ABC):
    """Abstract base class defining the minimal, explicit interface for all TrustRAG agents.

    Design Principles:
    - Explicitly typed inputs and outputs.
    - Deterministic where possible.
    - No uncontrolled autonomous loops.
    - Reusable and independently testable.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the unique identifier/name of the agent."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Return a human-readable description of the agent's role."""
        pass

    @abstractmethod
    def execute(self, *args: Any, **kwargs: Any) -> Any:
        """Perform the primary task of the specialized agent."""
        pass

    def run(self, *args: Any, **kwargs: Any) -> AgentResult:
        """Safely execute the agent with timing and standard AgentResult wrapping.

        Args:
            *args: Positional task arguments.
            **kwargs: Keyword task arguments.

        Returns:
            AgentResult instance containing the output or captured error.
        """
        start_time = time.perf_counter()
        try:
            output = self.execute(*args, **kwargs)
            elapsed = time.perf_counter() - start_time
            return AgentResult(
                agent_name=self.name,
                success=True,
                data=output,
                error_message=None,
                latency_seconds=elapsed,
            )
        except Exception as exc:
            elapsed = time.perf_counter() - start_time
            return AgentResult(
                agent_name=self.name,
                success=False,
                data=None,
                error_message=str(exc),
                latency_seconds=elapsed,
            )
